### PR TITLE
Updated index to add Rabbet info

### PR DESCRIPTION
**Pull request by johueri**

### CODE REVIEW

**Comment by handeyeco** [comment]
Hey @johueri, this is totally my bad but it looks like the address is "Austin, Texas" and the tests are expecting "Austin, TX." It also looks like since this was submitted, another PR was merged in causing a merge conflict (you'll need to fix the conflict by putting the entries in alphabetical order).

If you want help, feel free to comment here, ping me in Slack, or open the PR to allow editing by me: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by johueri** [comment]
Hey Matt, I updated the code; sorry for the delay. If there are any other
problems, please let me know.

**Comment by handeyeco** [comment]
Dang, it looks like the linter is throwing a fit over some whitespace: https://travis-ci.com/codementorship/austin-tech-list/builds/103256731

If you have npm installed, you can run the tests locally:

* Go to the root folder in the project on your computer in a terminal.
* Run `npm install` to install the development dependencies.
* Run `npm run check` to run the linting and tests.
  * This will point out where the error is occurring.
  * Once there are no more errors, it's safe to push!

That way you don't have to push a commit and wait for travis-ci to see if the tests pass. You can hit me up here or on Slack if you have questions.

**Comment by handeyeco** [comment]
Hey there! I went ahead and merged #98 which includes Rabbet. I'm going to close this PR, but let me know if you want to work together on a new PR. I've added some functionality that will hopefully make PRs easier.

**Pull request closed without merging**
